- name: copying mongo repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: present
  
- name: "get the catalogue entries count"
  ansible.builtin.shell:  mongo --host mongodb.76sdevops.website --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"


- name: "get the catalogue entries count"
  ansible.builtin.shell:  mongo --host mongodb.76sdevops.website --quiet --eval 'db = db.getSiblingDB("users"); db.products.count()'
  register: products_count
  when: component == "user"

- name: print the count
  ansible.builtin.debug:
    msg: "products count: {{products_count}}"


- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.76sdevops.website < /app/schema/catalogue.js
  when: component == "catalogue" and products_count.stdout == "0" # keep double quotes

- name: load users data
  ansible.builtin.command: mongo --host mongodb.76sdevops.website < /app/schema/catalogue.js
  when: component == "user" and products_count.stdout == "0" # keep double quotes  